### ISSUE TITLE
hitting enter on Y/n seems to be a no

### ISSUE THREAD

**Issue by tomholub** [seisvelas/S3-Exif-Cleaner#5]

**Comment by seisvelas** [comment]
That's intentional, I based the `-i` option on how `rm -i`, `xargs -p`, and GNU `parallel -p` work, where any non-explicitly affirmative response is interpreted as negative.

Since this tool is intended to be used on lots of images, that might be too onerous, so I've changed it to allow enter as a valid confirmation (like how `apt install` works)
